app/controller/auth.py
from werkzeug.security import check_password_hash, generate_password_hash
from flask_login import login_user, current_user
from flask import session, jsonify
from dependencies import bcrypt
from datetime import datetime
import pytz


class UserController:
    def __init__(self, user_model, user_repository):
        self.user_model = user_model
        self.user_repository = user_repository

        # print("Inside UserController object: ", user_model.password)

    def set_session(self, session_name: str, session_data):
        session[session_name] = session_data

    def validate_username_and_password(
        self, user_input_password, user_input_username
    ) -> bool:
        # self.user_model = True <- already checks if user exists or not
        if (
            self.user_model
            and bcrypt.check_password_hash(
                self.user_model.password, user_input_password
            )
            and len(user_input_password) < 50
            and self.validate_username(user_input_username)
        ):
            # baku_timezone_now = datetime.utcnow().replace(tzinfo=pytz.utc).astimezone(pytz.timezone('Asia/Baku'))
            #
            # if not self.user_model.is_admin and baku_timezone_now.weekday() > 4:
            #
            #     return False

            login_user(self.user_model)

            comnpany_joined_model = self.user_repository.join_with_company(
                current_user.id
            )

            session["company_id_pk"] = comnpany_joined_model.id
            session[
                "internal_company_name"
            ] = comnpany_joined_model.internal_company_name
            session[
                "internal_company_status"
            ] = comnpany_joined_model.internal_company_status
            session[
                "internal_company_balance_ref"
            ] = comnpany_joined_model.internal_company_balance_ref
            session["is_admin"] = self.user_model.is_admin
            session["all_user_roles"] = [
                int(i.role_fkey)
                for i in self.user_repository.get_all_user_roles(self.user_model.id)
            ]
            # session["keyword"] = [
            #     {}
            # ]

            # print(session['all_user_roles'])

            # TODO user-related global session values added here

            return True

        return False

    def validate_username(self, user_input_username):
        # self.user_model = True <- already checks if user exists or not
        if (
            self.user_model
            and len(user_input_username) < 50
            and not user_input_username.isdigit()
        ):
            return True

        return False

app/view/auth.py
from flask import Blueprint, jsonify, g, current_app
from werkzeug.security import check_password_hash, generate_password_hash
from flask_session import Session
from flask import (
    Flask,
    render_template,
    request,
    make_response,
    redirect,
    url_for,
    send_from_directory,
)
from flask_login import (
    LoginManager,
    login_user,
    logout_user,
    login_required,
    UserMixin,
    current_user,
)
from flask_cors import CORS
import os
from dependencies import db
from app.controller.auth import UserController, session
from app.view.webforms.login_form import LoginForm
from app.repository.keywords import KeywordsRepo


from app.repository.user import UserRepository

app = Blueprint("auth", __name__)


user_repository = UserRepository()
login_manager = LoginManager()
keyword_repo = KeywordsRepo()


@login_manager.user_loader
def load_user(user_id):
    try:
        return user_repository.find_by_id(user_id)

    except:
        return None


@app.route("/login", methods=["GET", "POST"])
def login():
    # print('DB SETTINGS: ', db.metadata)
    # print('DB SETTINGS: ', db.engines)

    title = "Giriş"

    login_form = LoginForm()

    if login_form.validate_on_submit():
        # user = user_repository.find_by_username(
        #     request.form['username'].lower())

        try:
            # returns user's model object with that username
            user = user_repository.find_by_username(request.form["username"].lower())

        except:
            # fixme
            return render_template(
                "./auth/login_view.html",
                title=title,
                is_error=True,
                error_msg="Bir xəta baş verdi!" " Zəhmət olmasa yenidən cəhd edin.",
                form=login_form,
            )

        # create an object for user_controller to check password
        user_controller = UserController(user, user_repository)

        if user_controller.validate_username_and_password(
            request.form["password"], request.form["username"].lower()
        ):
            if keywords_model := keyword_repo.get_current_keyword():
                model = keywords_model[0]

                print(
                    "I AM INSIDE (keywords_model := keyword_repo.get_current_keyword())"
                )
                print("SETTING USER SESSIONS AND KEYWORD")
                user_controller.set_session(
                    "keyword", {"week_no": model.week_no, "key": model.keyword}
                )

            if request.args.get("next"):
                return redirect(str(request.args.get("next")))

            if not session["is_admin"]:
                return redirect("/")

            else:
                # if 1 in session['all_user_roles']:
                #
                #     return redirect('/admin/all')

                return redirect("/admin/")

        # Zəhmət olmasa login və ya şifrənizi düzgün daxil edin!
        return render_template(
            "./auth/login_view.html",
            title=title,
            is_error=True,
            error_msg="Zəhmət olmasa login və ya şifrənizi düzgün daxil edin!"
            "və ya HƏFTƏ İÇİ daxil olmaqa çalışın.",
            form=login_form,
        )

    if not current_user.is_authenticated:
        return render_template("./auth/login_view.html", title=title, form=login_form)
    else:
        return redirect("/")

app/view/routes.py
from math import ceil
from app.middlewares.datetime_checker import date
import requests
from flask import Blueprint, jsonify, Response
from werkzeug.security import check_password_hash, generate_password_hash
from flask_session import Session
from flask import (
    Flask,
    render_template,
    request,
    make_response,
    redirect,
    url_for,
    session,
    send_from_directory,
)
from flask_login import (
    LoginManager,
    login_user,
    logout_user,
    login_required,
    UserMixin,
    current_user,
)
from flask_cors import CORS
import os
from app.controller.auth import UserController
from app.services.gcp_cloud_storage import VideoUploaderService
from app.view.webforms.login_form import LoginForm
from app.view.auth import user_repository
from dependencies import csrf
from app.view.video_upload import applications_repository


app = Blueprint("api", __name__)


@app.route("/favicon.ico")
def favicon():
    return send_from_directory(
        os.path.join(app.root_path, "../../static/img"), "favicon.ico"
    )


# keep in common view routes
@app.route("/logout")
@login_required
def logout():
    user = user_repository.find_by_id(current_user.get_id())

    if user:
        logout_user()
    return redirect("/login")


@app.route("/upload_u", methods=["POST"])
@date(request)
@csrf.exempt
def upldddoad():
    filename = request.headers.get("X-File-Name")
    file_size = int(request.headers.get("X-File-Size"))
    current_iter = int(request.headers.get("X-Current-Iter"))
    folder_uuid = str(request.headers.get("X-UUID"))

    iter_quantity = int(ceil(file_size / (1024 * 1024) / 30))

    # print(folder_uuid)
    if current_iter == 1:
        try:
            os.mkdir(os.environ.get("GOOGLE_STORAGE_LOCAL_DEST") + f"/{folder_uuid}")
        except FileExistsError:
            pass

    with open(
        os.environ.get("GOOGLE_STORAGE_LOCAL_DEST") + f"/{folder_uuid}/{filename}", "ab"
    ) as f:
        while True:
            chunk = request.stream.read(1024 * 1024 * 30)
            if not chunk:
                break
            f.write(chunk)

    if iter_quantity == current_iter:
        session["folder"] = folder_uuid
        session["filename"] = filename

        return "File uploaded successfully"

    return "Waiting for another chunk"

templates/base.html
<!DOCTYPE html>
{% block html_tag %}
<html class="h-full bg-gray-50">
  {% endblock %}
  <head>
    <meta charset="UTF-8" />
    <meta property="og:title" content="Fleet - Azerbaijan" />
    <meta
      property="og:image"
      content="{{ url_for('static', filename='img/fo_logo.svg') }}"
    />
    <meta
      property="og:description"
      content="Azərbaycan Fleet avtomobillərin idarəetmə paneli."
    />

    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <script
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"
      defer
    ></script>
    <link
      href="{{url_for('static',filename='dist/output.css')}}"
      rel="stylesheet"
    />
    <link
      href="{{url_for('static',filename='dist/custom.css')}}"
      rel="stylesheet"
    />
    <title>{{ title }}</title>
  </head>

  {% block body_tag %}
  <body>
    {% endblock %} {% block body_content %} {% endblock %}
  </body>
</html>

templates/base_auth.html
<!DOCTYPE html>
{% block html_tag %}
<html class="h-full bg-gray-50">
{% endblock %}
<head>
  <meta charset="UTF-8" />
  <meta property="og:title" content="Fleet - Azerbaijan" />
  <meta
          property="og:image"
          content="{{ url_for('static', filename='img/fo_logo.svg') }}"
  />
  <meta
          property="og:description"
          content="Azerbaijan. Fleet avtomobillərin idarəetmə paneli."
  />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <script
          src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"
          defer
  ></script>

  <script
          src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.js"
          defer
  ></script>

  <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.5/flowbite.min.css"
          rel="stylesheet"
  />

  <script
          src="{{url_for('static',filename='js/progressbar.js')}}"
          type="application/javascript"
          defer
  ></script>

  <link
          href="{{url_for('static',filename='dist/output.css')}}"
          rel="stylesheet"
  />
  <link
          href="{{url_for('static',filename='dist/custom.css')}}"
          rel="stylesheet"
  />

  <link
          rel="stylesheet"
          href="https://unpkg.com/@themesberg/flowbite@1.2.0/dist/flowbite.min.css"
  />

  <script
          src="https://unpkg.com/@themesberg/flowbite@1.2.0/dist/flowbite.bundle.js"
          defer
  ></script>
  <script src="https://unpkg.com/nprogress@0.2.0/nprogress.js" defer></script>
  <link
          rel="stylesheet"
          href="https://unpkg.com/nprogress@0.2.0/nprogress.css"
  />


  <link rel="stylesheet" href="{{url_for('static',
  filename='js/video-player-lazy-load-rtop/dist/css/rtop.videoPlayer.1.0.2.min.css')}}" />


    <script src="https://code.jquery.com/jquery-3.7.1.slim.js" integrity="sha256-UgvvN8vBkgO0luPSUl2s8TIlOSYRoGFAX4jlCIm9Adc=" crossorigin="anonymous"></script>


  <script type="text/javascript" src="{{url_for('static',
  filename='js/video-player-lazy-load-rtop/dist/js/rtop.videoPlayer.1.0.2.min.js')}}"></script>


  <script
          src="{{url_for('static',filename='js/custom.js')}}"
          type="application/javascript"
          defer
  ></script>

  <!-- <script src="https://cdn.rawgit.com/kimmobrunfeldt/progressbar.js/0.5.6/dist/progressbar.js"></script> -->
  <title>{{ title }}</title>
</head>
<header>
  <nav
          class="bg-white border-gray-200 px-2 sm:px-4 py-2.5 rounded dark:bg-gray-900"
  >
    <div
            class="flex flex-nowrap items-center justify-between mx-auto"
    >
      <a href="/" class="flex items-center">
        <img
                src="{{ url_for('static', filename='img/fo_logo.svg') }}"
                class="h-6 mr-3 sm:h-9"
                alt="Logo"
        />
      </a>



      <div class="flex space-x-2 md:order-2 md:space-x-2">

        <button
                type="button"
                class="mt-4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm ml-3 px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600"
                disabled
        >
          <div class="flex-row md:flex-row sm:flex-row">
            <div>
              Həftə №: {{ keyword["week_no"] }}
            </div>
            <div>
              Açar söz: {{ keyword["key"] }}
            </div>
          </div>

        </button>


        <button
                type="button"
                class="mt-4 text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center mr-3 md:mr-0 dark:bg-blue-600"
                disabled
        >
          {{ fleet_name }}
        </button>
        <button
                data-collapse-toggle="navbar-cta"
                type="button"
                class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-100 focus:outline-none focus:ring-2 focus:ring-gray-200 dark:text-gray-400 dark:hover:bg-gray-700 dark:focus:ring-gray-600"
                aria-controls="navbar-cta"
                aria-expanded="false"
        >
          <svg
                  class="w-6 h-6"
                  aria-hidden="true"
                  fill="currentColor"
                  viewBox="0 0 20 20"
                  xmlns="http://www.w3.org/2000/svg"
          >
            <path
                    fill-rule="evenodd"
                    d="M3 5a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 10a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1zM3 15a1 1 0 011-1h12a1 1 0 110 2H4a1 1 0 01-1-1z"
                    clip-rule="evenodd"
            ></path>
          </svg>
        </button>
      </div>

      <div
              class="hidden w-full md:block md:w-auto"
              id="navbar-cta"
      >
        <ul
                class="font-medium flex flex-col p-4 md:p-0 mt-4 border border-gray-100 rounded-lg bg-gray-50 md:flex-row md:space-x-8 md:mt-0 md:border-0 md:bg-white dark:bg-gray-800 md:dark:bg-gray-900 dark:border-gray-700"
        >

<!--          for highlight-->
          {% if '/tarixce' not in url_for(request.endpoint) and '/admin' not
          in url_for(request.endpoint) %}

          <li>
            <a
                    href="{{ url_for('video_upload.index_video_upload') }}"
                    class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"
                    aria-current="page"
            >Əsas</a
            >
          </li>
          <li>
            <a
                    href="{{ url_for('history.tarixce') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Sorğu tarixçəsi</a
            >
          </li>
          {% if session['is_admin'] == 1 %}
          <li>
            <a
                    href="/admin"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Admin-Panel</a
            >
          </li>
          {% endif %}
          <li>
            <a
                    href="{{ url_for('api.logout') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Çıxış</a
            >
          </li>

          {% elif '/tarixce' in url_for(request.endpoint) %}

          <li>
            <a
                    href="{{ url_for('video_upload.index_video_upload') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Əsas</a
            >
          </li>
          <li>
            <a
                    href="{{ url_for('history.tarixce') }}"
                    class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"
                    aria-current="page"
            >Sorğu tarixçəsi</a
            >
          </li>
          {% if session['is_admin'] == 1 %}
          <li>
            <a
                    href="/admin"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Admin-Panel</a
            >
          </li>
          {% endif %}
          <li>
            <a
                    href="{{ url_for('api.logout') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Çıxış</a
            >
          </li>

          {% else %}

          <li>
            <a
                    href="{{ url_for('video_upload.index_video_upload') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Əsas</a
            >
          </li>
          <li>
            <a
                    href="{{ url_for('history.tarixce') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Sorğu tarixçəsi</a
            >
          </li>
          {% if session['is_admin'] == 1 %}
          <li>
            <a
                    href="/admin"
                    class="block py-2 pl-3 pr-4 text-white bg-blue-700 rounded md:bg-transparent md:text-blue-700 md:p-0 dark:text-white"
                    aria-current="page"
            >Admin-Panel</a
            >
          </li>
          {% endif %}
          <li>
            <a
                    href="{{ url_for('api.logout') }}"
                    class="block py-2 pl-3 pr-4 text-gray-700 rounded hover:bg-gray-100 md:hover:bg-transparent md:hover:text-blue-700 md:p-0 md:dark:hover:text-white dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white md:dark:hover:bg-transparent dark:border-gray-700"
            >Çıxış</a
            >
          </li>



          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</header>

{% block body_tag %}
<body>
{% endblock %} {% block body_content %} {% endblock %}

<footer class="h-full bg-gray-50">
  <div class="bg-gray-50 inset-x-0 bottom-0 p-4">
    <div
            class="container flex flex-col items-center justify-between p-6 mx-auto space-y-4 sm:space-y-0 sm:flex-row"
    >
      <a href="/">
        <img
                class="w-auto h-7"
                src="{{ url_for('static', filename='img/fo_logo.svg') }}"
                alt=""
        />
      </a>

      <div class="flex -mx-2">
        <p class="text-sm text-gray-600 dark:text-gray-300">
          Balans artırma kodu: {{ internal_company_balance_ref }}
        </p>
      </div>
      <div class="flex -mx-2">
        <p class="text-sm text-gray-600 dark:text-gray-300">
          Azerbaijan
        </p>
      </div>
    </div>
  </div>
</footer>
</body>
</html>

templates/dynamic_table_test_gpt.html
<!DOCTYPE html>
<html>
<head>
	<title>Editable Table</title>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<script>
		// Function to handle the "Edit" button click event
		function handleEditButtonClick(event) {
			event.preventDefault();
			var form = document.createElement('form');
			form.action = 'process.php';
			form.method = 'POST';
			form.style.display = 'none';

			var table = document.getElementById('myTable');
			var rows = table.getElementsByTagName('tr');
			for (var i = 1; i < rows.length; i++) {
				var cells = rows[i].getElementsByTagName('td');
				for (var j = 0; j < cells.length; j++) {
					var input = document.createElement('input');
					input.type = 'hidden';
					input.name = 'data[' + (i-1) + '][' + j + ']';
					input.value = cells[j].innerText;
					form.appendChild(input);
				}
			}

			document.body.appendChild(form);
			form.submit();
		}

		// Function to add event listeners to the "Edit" button
		function addEditButtonListeners() {
			var buttons = document.getElementsByClassName('edit-button');
			for (var i = 0; i < buttons.length; i++) {
				buttons[i].addEventListener('click', handleEditButtonClick);
			}
		}

		// Function to initialize the table and add event listeners
		function initializeTable() {
			var table = document.createElement('table');
			table.id = 'myTable';

			var headerRow = document.createElement('tr');
			var nameHeader = document.createElement('th');
			nameHeader.innerText = 'Name';
			headerRow.appendChild(nameHeader);
			var ageHeader = document.createElement('th');
			ageHeader.innerText = 'Age';
			headerRow.appendChild(ageHeader);
			var emailHeader = document.createElement('th');
			emailHeader.innerText = 'Email';
			headerRow.appendChild(emailHeader);
			var editHeader = document.createElement('th');
			editHeader.innerText = 'Edit';
			headerRow.appendChild(editHeader);
			table.appendChild(headerRow);

			var data = [				{ name: 'John', age: '30', email: 'john@example.com' },				{ name: 'Mary', age: '25', email: 'mary@example.com' },				{ name: 'Peter', age: '40', email: 'peter@example.com' }			];

			for (var i = 0; i < data.length; i++) {
				var row = document.createElement('tr');
				var nameCell = document.createElement('td');
				nameCell.contentEditable = true;
				nameCell.innerText = data[i].name;
				row.appendChild(nameCell);
				var ageCell = document.createElement('td');
				ageCell.contentEditable = true;
				ageCell.innerText = data[i].age;
				row.appendChild(ageCell);
				var emailCell = document.createElement('td');
				emailCell.contentEditable = true;
				emailCell.innerText = data[i].email;
				row.appendChild(emailCell);
				var editCell = document.createElement('td');
				var editButton = document.createElement('button');
				editButton.innerText = 'Edit';
				editButton.className = 'edit-button';
				editCell.appendChild(editButton);
				row.appendChild(editCell);
				table.appendChild(row);
			}

			document.body.appendChild(table);

			addEditButtonListeners();

        }

// Initialize the table and add event listeners
document.addEventListener('DOMContentLoaded', function() {
    initializeTable();
    addEditButtonListeners();
});
</script>
</head>
<body>
</body>
</html>